services:
  lessonbooker:
    build:
      context: .
      dockerfile: LessonBooker/Dockerfile
    environment:
      - ASPNETCORE_ENVIRONMENT=Production
      - ConnectionStrings__DefaultConnection=${PROD_DB_CONNECTION}
      - FIREBASE_CREDENTIAL_PATH=/run/secrets/firebase-key.json
    volumes:
      - ${FIREBASE_CREDENTIAL_PATH}:/run/secrets/firebase-key.json:ro
    ports:
      - "80:8080"
