name: CD Backend

on:
  push:
    branches: [ "master" ]
  pull_request:
    branches: [ "master" ]

jobs:
  deploy:
    runs-on: ubuntu-latest
    steps:
      - name: Checkout code
        uses: actions/checkout@v2

      - name: Authenticate to Google Cloud
        uses: google-github-actions/auth@v2
        with:
          credentials_json: '${{ secrets.GCP_SA_KEY }}'

      - name: Set up Google Cloud SDK
        uses: google-github-actions/setup-gcloud@v1
        with:
          project_id: lessonbooker-8664a

      - name: Configure Docker for Google Artifact Registry
        run: gcloud auth configure-docker

      - name: Build Docker image
        run: |
          docker build -f LessonBooker/Dockerfile -t gcr.io/lessonbooker-8664a/lessonbooker:latest .

      - name: Push Docker image
        run: |
          docker push gcr.io/lessonbooker-8664a/lessonbooker:latest

      - name: Deploy new image to Cloud Run
        run: |
          gcloud run services update lessonbooker \
            --image gcr.io/lessonbooker-8664a/lessonbooker:latest \
            --region europe-west4 \
            --platform managed
